### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by jkvim** [jkvim/blog#4]
1. text vertical align
```css
div {
  vertical-align: middle;
  line-height: 20px;
}
```
[so](http://stackoverflow.com/questions/9249359/is-it-possible-to-vertically-align-text-within-a-div)
